//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jounce.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Jounce.Core.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The referenced property belongs to a different type..
        /// </summary>
        public static string BaseNotify_ExtractPropertyName_DifferentType {
            get {
                return ResourceManager.GetString("BaseNotify_ExtractPropertyName_DifferentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The referenced property does not have a get method..
        /// </summary>
        public static string BaseNotify_ExtractPropertyName_NoGetter {
            get {
                return ResourceManager.GetString("BaseNotify_ExtractPropertyName_NoGetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expression is not a member access expression..
        /// </summary>
        public static string BaseNotify_ExtractPropertyName_NotAMember {
            get {
                return ResourceManager.GetString("BaseNotify_ExtractPropertyName_NotAMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The member access expression does not access a property..
        /// </summary>
        public static string BaseNotify_ExtractPropertyName_NotAProperty {
            get {
                return ResourceManager.GetString("BaseNotify_ExtractPropertyName_NotAProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The referenced property is a static property..
        /// </summary>
        public static string BaseNotify_ExtractPropertyName_Static {
            get {
                return ResourceManager.GetString("BaseNotify_ExtractPropertyName_Static", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors messages should not be null..
        /// </summary>
        public static string BaseViewModel_SetErrors_NoNullErrors {
            get {
                return ResourceManager.GetString("BaseViewModel_SetErrors_NoNullErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ViewModel: {0}.
        /// </summary>
        public static string BaseViewModel_ToString_ViewModel {
            get {
                return ResourceManager.GetString("BaseViewModel_ToString_ViewModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EntityEvent : {0} : {1} : {2}.
        /// </summary>
        public static string EntityEvent_ToString_EntityEvent {
            get {
                return ResourceManager.GetString("EntityEvent_ToString_EntityEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MEF: Found catalog: {0}.
        /// </summary>
        public static string MefDebugger__dbgMefCatalog_MEF__Found_catalog {
            get {
                return ResourceManager.GetString("MefDebugger__dbgMefCatalog_MEF__Found_catalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to       With key: {0} = {1}.
        /// </summary>
        public static string MefDebugger__dbgMefKey {
            get {
                return ResourceManager.GetString("MefDebugger__dbgMefKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MEF: Found part: {0}.
        /// </summary>
        public static string MefDebugger__dbgMefPart_MEF__Found_part {
            get {
                return ResourceManager.GetString("MefDebugger__dbgMefPart_MEF__Found_part", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    With export:.
        /// </summary>
        public static string MefDebugger__dbgMefWithExport_With_export {
            get {
                return ResourceManager.GetString("MefDebugger__dbgMefWithExport_With_export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    With import: {0}.
        /// </summary>
        public static string MefDebugger__dbgMefWithImport_With_import {
            get {
                return ResourceManager.GetString("MefDebugger__dbgMefWithImport_With_import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    With key: {0} = {1}.
        /// </summary>
        public static string MefDebugger__dbgMefWithKey {
            get {
                return ResourceManager.GetString("MefDebugger__dbgMefWithKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added Export:.
        /// </summary>
        public static string MefDebugger__msgAddExport_Added_Export {
            get {
                return ResourceManager.GetString("MefDebugger__msgAddExport_Added_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed contracts:.
        /// </summary>
        public static string MefDebugger__msgChangeContract_Changed_contracts {
            get {
                return ResourceManager.GetString("MefDebugger__msgChangeContract_Changed_contracts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed Export:.
        /// </summary>
        public static string MefDebugger__msgChangedExport_Removed_Export {
            get {
                return ResourceManager.GetString("MefDebugger__msgChangedExport_Removed_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MEF Debugger shutting down..
        /// </summary>
        public static string MefDebugger_Close_MEF_Debugger_shutting_down {
            get {
                return ResourceManager.GetString("MefDebugger_Close_MEF_Debugger_shutting_down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ViewModelRoute: {0} binds to {1}.
        /// </summary>
        public static string ViewModelRoute_ToString_ViewModelRoute {
            get {
                return ResourceManager.GetString("ViewModelRoute_ToString_ViewModelRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate.
        /// </summary>
        public static string ViewNavigationArgs_ToString_Activate {
            get {
                return ResourceManager.GetString("ViewNavigationArgs_ToString_Activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivate.
        /// </summary>
        public static string ViewNavigationArgs_ToString_Deactivate {
            get {
                return ResourceManager.GetString("ViewNavigationArgs_ToString_Deactivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ViewNavigation : {0} {1}.
        /// </summary>
        public static string ViewNavigationArgs_ToString_ViewNavigation {
            get {
                return ResourceManager.GetString("ViewNavigationArgs_ToString_ViewNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Route: View {0} in XAP {1}.
        /// </summary>
        public static string ViewXapRoute_ToString_View_Route_View {
            get {
                return ResourceManager.GetString("ViewXapRoute_ToString_View_Route_View", resourceCulture);
            }
        }
    }
}
