//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jounce.Regions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Jounce.Regions.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control not found: {0}.
        /// </summary>
        internal static string RegionAdapterBase_ValidateControlName_Control_not_found {
            get {
                return ResourceManager.GetString("RegionAdapterBase_ValidateControlName_Control_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region not found: {0}.
        /// </summary>
        internal static string RegionAdapterBase_ValidateRegionName_Region_not_found {
            get {
                return ResourceManager.GetString("RegionAdapterBase_ValidateRegionName_Region_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request to activate view {0}.
        /// </summary>
        internal static string RegionManager_ActivateView_Request_to_activate_view {
            get {
                return ResourceManager.GetString("RegionManager_ActivateView_Request_to_activate_view", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request to deactivate view {0}.
        /// </summary>
        internal static string RegionManager_DeactivateView_Request_to_deactive_view {
            get {
                return ResourceManager.GetString("RegionManager_DeactivateView_Request_to_deactive_view", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added region {0}.
        /// </summary>
        internal static string RegionManager_RegisterRegion_Added_region {
            get {
                return ResourceManager.GetString("RegionManager_RegisterRegion_Added_region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region type {0} is not supported..
        /// </summary>
        internal static string RegionManager_RegisterRegion_Region_type_is_not_supported {
            get {
                return ResourceManager.GetString("RegionManager_RegisterRegion_Region_type_is_not_supported", resourceCulture);
            }
        }
    }
}
