//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jounce.Framework {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Jounce.Framework.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jounce Error: No view was flagged as the shell view..
        /// </summary>
        internal static string ApplicationService_Starting_Jounce_Error_No_view {
            get {
                return ResourceManager.GetString("ApplicationService_Starting_Jounce_Error_No_view", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} : Shell resolved to {1}.
        /// </summary>
        internal static string ApplicationService_Starting_ShellResolved {
            get {
                return ResourceManager.GetString("ApplicationService_Starting_ShellResolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished loading module {0}.
        /// </summary>
        internal static string DeploymentService_DeploymentCatalogDownloadCompleted_Finished {
            get {
                return ResourceManager.GetString("DeploymentService_DeploymentCatalogDownloadCompleted_Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load required module. Please contact the system administrator..
        /// </summary>
        internal static string DeploymentService_DeploymentCatalogDownloadCompleted_ModuleNotFound {
            get {
                return ResourceManager.GetString("DeploymentService_DeploymentCatalogDownloadCompleted_ModuleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XAP name should end with .xap extension..
        /// </summary>
        internal static string DeploymentService_RequestXap_XAPExtensionError {
            get {
                return ResourceManager.GetString("DeploymentService_RequestXap_XAPExtensionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} : activate view {1}.
        /// </summary>
        internal static string ViewModelRouter_ActivateView {
            get {
                return ResourceManager.GetString("ViewModelRouter_ActivateView", resourceCulture);
            }
        }
    }
}
